### ISSUE TITLE
can harvest pelts from animals but floating text says that "You can't harvest with that tool"

### ISSUE THREAD

**Issue by garbfink** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#1]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release

**bug Report**
killed some badgers and deer, click on carcass and floating text appears saying "You can't harvest with that tool" However, pelt still appears in inventory.

tested with no weapon attached and floating text does not appear, pelt still appears in inventory.

I tried with Green greataxe, green warhammer, and blacksouls sickle all with the same result as above.

**To Reproduce**
kill badger or dear,
with weapon equipped click on carcass

**Comment by Samuel-IH** [comment]
The fix for this will be available next time we patch the alpha server.
