### ISSUE TITLE
Epic Skill Focus doesn't show as Harvest etc

### ISSUE THREAD

**Issue by ExtraneousVariable** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#10]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release
Windows 10

**Describe the bug**
If you take enough skills to qualify for epic skill focus in the harvesting/mastery etc it doesn't show as those, instead it still shows as Craft Armor, Craft Trap, Craft Weapon.

**To Reproduce**
Take epic skill focus in a crafting.

**Screenshots**
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/10efdc06-972e-4052-81eb-32d094e298a9)

**Comment by Samuel-IH** [comment]
Fixed
