### ISSUE TITLE
Red Palm yields Pine Wood

### ISSUE THREAD

**Issue by Stridsvogn** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#11]
Found some Red Palm trees, but when I chopped them down and looted them they all gave Pine Wood instead of Red Palm Wood.

EDIT: I chopped several Red Palms, they all gave Pine Wood.

![got wood](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/156006813/813e6888-9fe9-4563-ba32-7748dfa0001c)

**Comment by Samuel-IH** [comment]
Fixed. Will be available next time the server gets patched.
