### ISSUE TITLE
smelting down gts crafted weapons yield wood as well as ingots

### ISSUE THREAD

**Issue by garbfink** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#12]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release

**Describe the bug**
Unsure if bug but it doesn't seem right that if I smelt down a crafted weapon, then a proportion of the wood used for the weapon is also returned.

**To Reproduce**
smelt down crafted weapon

**Screenshots**

**Comment by Samuel-IH** [comment]
Works as intended. This allows the wood to be consumed emulating the tool handle being used as fuel.
