### ISSUE TITLE
Can't craft copper coif or any shield

### ISSUE THREAD

**Issue by garbfink** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#13]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release

**Describe the bug**
All ingredients are showing as green, click on craft item, item appears in crafting queue but no progress bar is visible and item is not crafted.

Relogged and problem persists

**To Reproduce**
select copper coif or copper shield from crafting menu

**Screenshots**
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/155997230/2d1697c2-3c07-43bd-9a52-525407720b55)

**Comment by Samuel-IH** [comment]
The issue here is that the crafting range is too small. Step a bit closer to the crafting station.
I'll adjust this for the next patch.
