### ISSUE TITLE
Pelts can be gained without proper tool, and have zero weight until stored in Vault and retrieved

### ISSUE THREAD

**Issue by ExtraneousVariable** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#15]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release
Windows 10

**Describe the bug**
Pelts can be obtained even though it says "You can't harvest with that tool!"
Also, pelts have zero weight unless you put them in the Vault and pull them back out again.

**To Reproduce**
Skin anything.  Inventory fills with zero weight pelts, even with a mining hammer or any weapon at all equiped.

NOTE: I am not averse to being able to skin without having to swap weapons.  I actually prefer being able to harvest with any weapon, but it might make sense to just have it check that you POSSESS a skinning tool, and if you have one on your character, great he pulls out his knife and skins it.  Swapping weapons to skin a badger gets tedious.

**Screenshots**
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/99abe124-e362-4731-9990-ac9949f728a1)

**Comment by Samuel-IH** [comment]
Both of these are fixed and should be available next time the server gets patched.
