### ISSUE TITLE
Ore is spawning on top of existing objects.

### ISSUE THREAD

**Issue by ExtraneousVariable** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#16]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release
Windows 10

**Describe the bug**
Ore is spawning on top of existing placeables like chairs etc.

**To Reproduce**
Go to an area with placeables.  I was in the Benzor River Valley Orc Caves

**Screenshots**
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/ab57179a-4be9-4880-b45e-df89e0099954)

**Comment by Samuel-IH** [comment]
For performance reasons this will not be fixed.
