### ISSUE TITLE
Copper Daggers in the Forge are not smelting down

### ISSUE THREAD

**Issue by ExtraneousVariable** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#17]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release
Windows 10

**Describe the bug**
Add pine/elm to forge, let it get hot.  Copper Daggers just sit there.  Fuel is consumed, nothing happens.

**To Reproduce**

**Screenshots**
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/6b566278-def6-4c20-8feb-60cda225d1b5)

**Comment by Samuel-IH** [comment]
Closing. This is the same as: https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/issues/24
