### ISSUE TITLE
Ammunition Crafting - small stack vs large bundle not calculating success/mastery properly

### ISSUE THREAD

**Issue by ExtraneousVariable** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#18]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release
Windows 10

**Describe the bug**
Leveling up Bullets produces 5 at a time, and is slow and consumes a lot of material.  Understandable, sort of.
Once leveled up, with 143% success and 43% Mastery, I can consistently make the bullets.  However, the bulk creation option doesn't reflect the skill of copper bullets.  I can't level it up, it has [0/0] as the needed leveling criteria.

**To Reproduce**
Make copper bullets
Try to make batches of bullets.
Fail due to low Success and Mastery.

**Screenshots**
Trying to bulk create:
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/139e7961-7b25-469b-957d-7d0bcff9fb2c)

Individual create is high percentages.
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/d1c90f38-0cb2-453b-9b0b-ff20130681d6)

**Comment by ExtraneousVariable** [comment]
Also, I don't think 5 and 50 bullets vs the amount of copper and pine required lines up.  Effort vs reward is too low.  I think a stack of 99 per ingot/wood would be more reasonable.  And bulk creation is definitely awesome, that helps a lot, but should make 5 stacks per 5 input elements.  Otherwise I cannot see anyone making much of these, they'll just stick to unlimited Nords etc.

**Comment by ExtraneousVariable** [comment]
Also, it doesn't appear that Masterful Bullets are being generated.  Possibly on purpose?

**Comment by Samuel-IH** [comment]
This has been fixed and will be available next time we patch the alpha server.

Mastery for ammunition, Mastery in general, and the balance between resource and output will be considered at a later date.
