### ISSUE TITLE
Old ATS item levels don't match their levels on Prod

### ISSUE THREAD

**Issue by ExtraneousVariable** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#19]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release
Windows 10

**Describe the bug**
Item level restrictions for ATS items on production are lower than on the test system.  This isn't a big deal for high level characters, but if this was pushed today, some characters would no longer be able to equip items that they can currently wear today.  These get unequipped upon login.

**To Reproduce**
Check Item Level Requirements of Prod vs the test system.  This seems to be affecting many items.

**Screenshots**
One specific example (there are many)
GTS system of an old ATS amulet has ILR 21 for Smooth Syenite Ideal Black Sapphire Amulet
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/4dc5cc59-9089-46d1-9108-dd780afb84ce)

That same item in Prod is Level 18.
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/7d3b2a8b-0a1b-40fc-b21f-613c1a0e68ff)

**Comment by Samuel-IH** [comment]
Unrelated to GTS.

Still, @TomRotfl was this an intentional change?

**Comment by Samuel-IH** [comment]
Oh, maybe this is just because the ATS scripts have been gutted.

**Comment by TomRotfl** [comment]
Correct ATS scripts are completely gone. ATS items still exist on the alpha server but that is just temporary, ignore them!
