### ISSUE TITLE
Cant' sell to mulrock trade skills merchant

### ISSUE THREAD

**Issue by garbfink** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#2]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release

**Describe the bug**
Testing whether I could sell craftged items to the mulrock trade hall merchant. this cannot be done. However floating text does say "This merchant accepts GTS items only"

**To Reproduce**
make something, go try sell it.

**Screenshots**

**Comment by Samuel-IH** [comment]
Interesting that the merchants have already been updated to use the phrase "GTS" instead of "ATS".

I've updated the labels in this issue as this is a planned feature that hasn't been implemented yet. This issue will be closed when the feature is in the game.

**Comment by ExtraneousVariable** [comment]
At the moment, it appears you can sell the crafted items to anyone.

**Comment by TomRotfl** [comment]
Yes we haven't implemented a system to filter GTS items to merchants, it will come later on
