### ISSUE TITLE
Old ATS items are no longer providing set bonuses amongst themselves.

### ISSUE THREAD

**Issue by ExtraneousVariable** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#20]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release
Windows 10

**Describe the bug**
The ATS system appears to be disabled for set bonuses.  I'm guessing this is intentional, but reporting anyway.

**To Reproduce**
Put on an ATS item set.  No temporary bonuses appear.

**Screenshots**
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/8bba4944-64b4-4d9c-bd69-6ef42108eb49)

**Comment by Samuel-IH** [comment]
Unrelated to GTS.

Probably same as this:
https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/issues/19#issuecomment-1883965879
