### ISSUE TITLE
Incomplete item appearances

### ISSUE THREAD

**Issue by TomRotfl** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#21]
As explained by Extraneous "A copper Greataxe looks identical to a Rubicite Greataxe". Better check all items from all tiers to try to have them look a bit different when there will be the time for it

**Comment by Samuel-IH** [comment]
Some of the item's appearances hasn't been set up yet -- leaving them with blank icons and default (gray) appearances.

Also some of the low tier items have the same appearances as high tier items. This is not always an issue but in some cases not desired.

**Comment by Samuel-IH** [comment]
If you wish to report an item with an incorrect or missing appearance, drop it in a comment here.

**Comment by BarchamMal** [comment]
Bows do not have appearances.

This is the appearance info:
| Weapon | Max-Model-Number | Max-Color-Number |
|--------|--------|--------|
| Longbow | 8 | 4 |
| Shortbow | 6 | 4 |

**Comment by BarchamMal** [comment]
Crossbows do not have appearances.
Slings do not have appearances.
Helmets do not have appearances.
Cloaks do not have appearances.

This is the appearance info:

| Weapon | Max-Model-Number | Max-Color-Number |
|--------|--------|--------|
| Heavy Crossbow | 4 | 4 |
| Light Crossbow | 4 | 4 |

**Comment by Samuel-IH** [comment]
_Complete._
