### ISSUE TITLE
Unable to Cut Jade

### ISSUE THREAD

**Issue by HiroRogue** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#23]
**Your setup**
Device platform:  MacOS

**Describe the bug**
Unable to cut jade, I have in inventory but It doesn't show in window when I try to cut

**Screenshots**

**Comment by HiroRogue** [comment]
Hence unable to unlock emerald cutting

**Comment by Samuel-IH** [comment]
This one's already fixed, and will be available when the server gets patched next.
