### ISSUE TITLE
Some low-tier items have the same stats as high-tier items

### ISSUE THREAD

**Issue by HiroRogue** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#25]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release

**Describe the bug**

**To Reproduce**

**Screenshots**

**Comment by Samuel-IH** [comment]
This is due to the fact that a lot of the items are _meant_ to have the same main stats, but offstats like skills would go up. Right now the item stats are very barebones but in the future there will be skill bonuses and saving throws and such.

**Comment by Samuel-IH** [comment]
Going to close any dupes of this card and reference the reported items in comments.

**Comment by Samuel-IH** [comment]
- Shadowsteel + mithral amulets
- Yellow + blue boots
- Gold + silver boots

**Comment by Samuel-IH** [comment]
The items stats are now complete. They will be available next patch.
