### ISSUE TITLE
Have higher tiered minables only allow to be collected using higher tier equiment

### ISSUE THREAD

**Issue by garbfink** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#28]
**Is your feature request related to a problem? Please describe.**
Currently it would appear that any rock or tree can be gathered by any kind of equiment. I believe that the more exotic a material is the harder it should be to obtain.

**Describe the solution you'd like**
Implement a system where a player can only mine an ore that is 1 tier higher that then equipment they are using. e.g. copper can be mined with anything, iron has to be mined with copper, and so on, Can be done with gems and trees as well.

The higher up the rank of material you equip, the more efficient the process is for gathering materials that are below. so a verdicite (ignore the whole acid thing for this example) hammer would net you like 25 copper, 20 iron, 15 whatever the next tier is and so on.

I think that this adds a bit more depth and prolongs the crafting game a little longer.

**Describe alternatives you've considered**
Don't have restriction on what can be mined however severely lower the efficiency for mining something out of your gears range. so mining verdicite with a copper happy will net you 1 ore, but mining it with a iron hammer will net you 3 and so on.

**Additional context**

**Comment by Samuel-IH** [comment]
Closing this. I've playtested it and have decided there is enough incentive already to upgrade to higher tier equipment. No need to impose this as a restriction.
