### ISSUE TITLE
Weapon specific window is behind the flow diagram window

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#29]
I'm running on Windows PC in windowed mode.

When I select copper light hammer the new window that allows you to create the hammer is drawn beneath the existing flow chart window making it difficult to see that something happens when I clicked on the weapon to craft.

**Comment by Samuel-IH** [comment]
Not a bug. That's kind of how Nui works.

You can resize and move the crafting tree so that you can drag out the recipe window from underneath. Once you manually close the recipe window or crafting tree they will remember their positions for next time.
