### ISSUE TITLE
Fatal Error occoured while using Forge

### ISSUE THREAD

**Issue by garbfink** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#3]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release

**Describe the bug**
Think this possibly could be on the client side but I don't know how to double check. 
I was using the forge, Placed some elm in. went to examine pine which was in my inventory and a fatal error occoured.

I have logged back on and tried to recreate but all seems ok. I have included crash log and dump if that helps.

**To Reproduce**
open forge,
insert elm
examine pine trhough radial menu.
[nwmain-crash-1704732249.dmp](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/files/13864176/nwmain-crash-1704732249.dmp)
[nwmain-crash-1704732249.log](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/files/13864177/nwmain-crash-1704732249.log)

**Screenshots**

**Comment by Samuel-IH** [comment]
Merged this into #36
