### ISSUE TITLE
If you queue more items than you have resources all crafting stops

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#30]
I have 83 iron ingots
I'm trying to craft iron greataxe that takes 5 ingots so I see 83/5

If I add to axes to the queue it starts crafting, if I then add to 10 everything just stops and I have to dequeue the extras.

Shouldn't it just limit how many can be added to the queue and only add 16 instead of just stopping everything?

**Comment by dpeart** [comment]
After this happens you have to close all crafting windows and start over

**Comment by Samuel-IH** [comment]
@dpeart I wasn't able to reproduce this. Can you attach a screencap of this issue? The only thing that i know of that would just pause the crafting would be stepping away from the crafting station.

**Comment by dpeart** [comment]
I've not been able to reproduce.  Maybe it was because my inventory got full and I didn't notice.
