### ISSUE TITLE
Animals killed for hides do not respawn

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#31]
I waited overnight, but they never respawned.

**Comment by dpeart** [comment]
If I skin the animal it doesn't respawn. If you go to black hills you can see that I've killed every animal there, that you can get to.

**Comment by dpeart** [comment]
I wonder if this respawn issue is because eventually they all did respawn but in the areas where you can't hunt them.  so they reach their max animal density and just stay there.

I've been all over and not seen a respawn issue anywhere else.

**Comment by dpeart** [comment]
since the reboot I have seen animals respawn in black hills, so I believe the issue is that they are just where you cannot get to them.

**Comment by Samuel-IH** [comment]
Animal spawns have been adjusted, but the possibility of them spawning out of reach is still possible. This is more or less a side effect of the proc gen system, and is unlikely to be changed anytime soon. Closing this.
