### ISSUE TITLE
Animal corpses don't despawn if not skinned

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#32]

**Comment by Samuel-IH** [comment]
@dpeart is this any different than issue #31 ?

**Comment by dpeart** [comment]
I killed an animal, but didn't skin it.  The corpse stayed there for over 30 minutes. so it is different.

This was in black hills,

**Comment by Samuel-IH** [comment]
Oh. Despawn vs respawn. I see

**Comment by Samuel-IH** [comment]
Fixed next patch. These will despawn after 5 mins now.
