### ISSUE TITLE
After stopping crafting by wings/walking away GUI is messed up on restarting

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#35]
I'm smithing weapons.  I queued up a lot of things and walked/wings away to stop the crafting.

When I came back and resumed crafting the current item being crafted no longer shows its name in but instead a constantly changing number between 0 and 1

After it filled up my inventory the number stops changing and is a 0.

**Comment by Samuel-IH** [comment]
Can't seem to reproduce this.

**Comment by BarchamMal** [comment]
This issue is almost 2 months old without anyone being able to reproduce it. Should it be closed as stale?

**Comment by dpeart** [comment]
Yes, I've not had the issues since
