### ISSUE TITLE
You can skin an animal with your bare hands!!

### ISSUE THREAD

**Issue by BarchamMal** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#38]
Device platform: MacOS (but doesn't matter)
Game version: I've no idea

Kill an animal with a knife, skin it with a knife. ✅ 
Kill an animal with a hammer, skin it with a hammer. ❌ 
Kill an animal with your bare hands, skin it with your bare hands. ✅ 

**To Reproduce**
1. Walk over to an animal
2. Look it in the eye
3. Judge if you think you're a match for it
4. Note that you're lvl 40
5. Kill it in 1 punch
6. Skin it with your bare hands
7. Contemplate how horrifically complicated that was

**Comment by Samuel-IH** [comment]
>     5. Kill it in 1 punch
One puuunchh!!!
![giphy](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/46057508/118cc6a3-fbe1-45f3-8269-52b67c5b68a5)

It's fixed though.
Will be available next patch
