### ISSUE TITLE
Procedurally generated animals respawn immediately

### ISSUE THREAD

**Issue by BarchamMal** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#39]
**Your setup**
Device platform: MacOS (but it doesn't matter)
Game version: no matter.

Animals respawn as soon as their corpse fades away.

**To Reproduce**
1. I kill an animal
2. I harvest it with my bare hands (#38)
3. As soon as the corpse fades away, the alive animal respawns

**Screenshots**
I have a video but its 29.5 MB

**Comment by Samuel-IH** [comment]
Fixed next patch
