### ISSUE TITLE
Quite a few trees spawning in the skin shop

### ISSUE THREAD

**Issue by garbfink** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#4]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release

**Describe the bug**
As per description

**To Reproduce**
Go to skin shop.

**Screenshots**
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/155997230/3a41741a-e1d4-41be-97c3-0b28a80c1063)

**Comment by Samuel-IH** [comment]
@TomRotfl Can you handle this one? I think this area needs that one var that makes GTS ignore it. Please close the issue when it's fixed.

**Comment by TomRotfl** [comment]
Ah yes, I need to exclude the area manually

**Comment by TomRotfl** [comment]
Fixed
