### ISSUE TITLE
When making leather the queue only shows Leather no the skin being turned to leather

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#40]
For everything else the queue will state what is being created.  I guess it is true that in this case it is all leather, but seeing the animal lets you know what is being worked on, and makes a big difference as to the final number of leather created.

![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/5182846/bae7f044-cfaa-4cd5-a73e-6917337018dd)

**Comment by Samuel-IH** [comment]
Works as intended, but would be nice if the I had that extra info.

**Comment by Samuel-IH** [comment]
Closing this. It's been combined into a feature request.
