### ISSUE TITLE
Monks dont get set bonus on gloves

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#41]
I checked with my monk using Nordock and it does get set bonuses to the gloves.

I don't see that for GTS gear.  A monk does get set bonus on weapons, but not gloves.

**Comment by Samuel-IH** [comment]
I'm getting set bonuses
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/46057508/8d8f8ef4-fc64-450d-b676-bd9f2676ff6a)

**Comment by dpeart** [comment]
I have crafted armor, ammy and gloves, no set bonus. and I'm using red gloves as well.

Is it a different set?

**Comment by dpeart** [comment]
When I swapped to non-masterful gloves it works.  Masterful gloves don't.

**Comment by Samuel-IH** [comment]
Masterful working for me too:
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/46057508/9b1380b7-d893-4834-a327-c5d3d71378fc)

**Comment by Samuel-IH** [comment]
@dpeart did you make your pair of masterful gloves more than a week ago?

**Comment by dpeart** [comment]
I don't think so, but maybe?

**Comment by Samuel-IH** [comment]
@dpeart The set bonuses were implemented recently (last week) and any items made before them wont have set bonuses.
Please try with a new pair if you can.

**Comment by dpeart** [comment]
YOu can close this. I don't know what I did but it is working now.
