### ISSUE TITLE
The ? for success and mastery provides the same info

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#42]
On the crafting GUI you can select the ? for more details regarding Craft Speed, success and mastery. 

Success and Mastery provides all the information.  I think a single ? would work fine.

**Comment by Samuel-IH** [comment]
Wontfix.

Leaving the two buttons in case we change the calculation for one, or add tip info into the help window.
