### ISSUE TITLE
If a crafting window is in top left and you open the forge the UI is drawn wierd

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#43]
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/5182846/d4c629e9-88fe-4b6f-93cf-d4c6e1fd35aa)

**Comment by dpeart** [comment]
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/5182846/db359327-8255-4097-9aee-125d0538e860)

**Comment by Samuel-IH** [comment]
Not a bug. Just one window in front of another.

Unfortunate consequence of Nui
