### ISSUE TITLE
Boots crafting doesn't show the boot image

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#44]
I'm not sure what happened, I've never seen it before, but I got a picture.

When I clicked on the crafting again the client crashed.

![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/5182846/157bf641-bd5f-4d1a-a80b-a1e8ffd64a93)

**Comment by Samuel-IH** [comment]
Dupe of https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/issues/21
