### ISSUE TITLE
don't smelt leather into salt

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#46]
No one wants their leather (the most expensive to get ingredient) to be smelted into salt an ingredient that makes game play difficult because there is so much of it.

and I accidentally put my entire stack of ~100 leather into the smelter. An expensive way to get salt :)

**Comment by Samuel-IH** [comment]
I also ran into this "behavior". Quite annoying.

**Comment by Samuel-IH** [comment]
This issue was combined into a feature request, closing.
