### ISSUE TITLE
CRASH ISSUE!!! Burning trees crashes the server.

### ISSUE THREAD

**Issue by BarchamMal** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#48]
**Your setup**
Device platform: no matter, its serverside.
Game version: dunno.

**Describe the bug**
After setting a tree on fire (with a torch) and it falling down, setting it on fire again (with a torch) will about 60% of the time crash the server.

**To Reproduce**
1. Set a tree on fire with a torch.
2. Let it burn down and fall over.
3. Set it on fire, quick before it disappears.
4. Most likely the server will now crash.

**Comment by Samuel-IH** [comment]
Fixed
