### ISSUE TITLE
Name problem. Not a bug or enhancement really.

### ISSUE THREAD

**Issue by BarchamMal** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#49]
This:
<img width="147" alt="IMG_5612" src="https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/115943779/b4ad0f79-af14-4478-a63f-7352b121d6c6">
Should be named that:
```ColdIron Ore Vein```

**Comment by Samuel-IH** [comment]
Fixed
