### ISSUE TITLE
Masterful no additional stats

### ISSUE THREAD

**Issue by Stridsvogn** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#5]
Not sure if this is intentional or not, but Masterful crafted weapons have the exact same stats as regular ones.
IE, Masterful Crafted Iron Warhammer is +1 Enhance and +2d6 Bludgeoning Damage, same as regular Crafted Iron Warhammer. It's the same with every other weapon I've crafted so far.

**Comment by Samuel-IH** [comment]
Closing this as wontfix. This feature is not intended for GTS as the masterful items will receive their bonus via set bonuses.
