### ISSUE TITLE
In a furnace: "Steel or Non-Steel?"

### ISSUE THREAD

**Issue by BarchamMal** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#50]
**Your setup**
Device platform: MacOS
Game version: Same as all my issues. SERVER SIDE!

**Describe the bug**
If you have charcoal and non-steel ores (salt, copper, iron, mithril) in a furnace, they will not smelt.
Logical error I think. I wonder if the code goes like this:
```py
if forge.inventory.has_item(charcoal):
    for item in forge.inventory:
        forge.try_to_smelt_recipe(item, charcoal)
else:
    for item in forge.inventory:
        forge.try_to_smelt_recipe(item)
```

When it should be:
```py
if forge.inventory.has_item(charcoal):
    for item in forge.inventory:
        if not forge.try_to_smelt_recipe(item, charcoal):
            forge.try_to_smelt_recipe(item)
else:
    for item in forge.inventory:
        forge.try_to_smelt_recipe(item)
```

**To Reproduce**
1. Put wood in a furnace to heat it up.
2. After it is heated, put charcoal and iron in the furnace.
3. The furnace will cool back down and nothing will get smelted.

**Comment by Samuel-IH** [comment]
@BarchamMal we need to get you on discord so you can join the team. I swear C# is like Java but better!

**Comment by BarchamMal** [comment]
that was python.

**Comment by Samuel-IH** [comment]
Obviously. But I know you know Java.

**Comment by BarchamMal** [comment]
Oh good.

**Comment by BarchamMal** [comment]
Was my guess correct?

**Comment by Samuel-IH** [comment]
No. Charcoal is just part of the recipe.

**Comment by BarchamMal** [comment]
Then why doesn't iron, salt, or copper smelt when charcoal is in the furnace?

**Comment by Samuel-IH** [comment]
It was an iteration issue. Looping through an inventory while I'm already looping through the same inventory. Interop stuff.
