### ISSUE TITLE
Heat bar exceeds outline.

### ISSUE THREAD

**Issue by BarchamMal** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#51]
**Your setup**
Device platform: MacOS
Game version: dunno

**Describe the bug**
I heated up the furnace to like 2900° (I think) and the heat exceeded the outline.
The visual heat bar should be clamped to the outline size.

**To Reproduce**
Heat up the furnace to past 2900° (I think) and you will see the bug.

**Screenshots**
<img width="500" alt="image" src="https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/115943779/12380809-e028-4208-b409-1bddf64d7c45">

**Comment by Samuel-IH** [comment]
Fixed, maybe. I clamped the value so if that doesn't fix it then it's an nwn client issue.

**Comment by BarchamMal** [comment]
Clamped the serverside temperature value?
So it can't get hotter than 2900°?

**Comment by Samuel-IH** [comment]
@BarchamMal No. Clamped the value that gets bound to the progress bar to a 0-1 range.
