### ISSUE TITLE
Under Ammunition, why are the bullets repeated twice?

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#52]
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/5182846/36cfa76c-f562-431c-ad0b-a43510820faa)

**Comment by BarchamMal** [comment]
This is intended. After you master crafting them, you can craft them in bulk.
The first is 5 bullets (or arrows or bolts), the second is 50.

**Comment by Samuel-IH** [comment]
Related to #40

**Comment by Samuel-IH** [comment]
Closing this. It's been combined into a feature request.
