### ISSUE TITLE
Bug that stops plants/dyes spawning.

### ISSUE THREAD

**Issue by BarchamMal** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#56]
**Describe the bug**
I've found a bug which stops plant/dyes from spawning.

**To Reproduce**
1. Click on an anvil.
2. Open a shadow steel weapon
3. Examine snakewood.
4. Wait a few (3-10) minutes, possibly examine other stuff, maybe Elanor.
5. Examine red sumac and it should not show that it spawns anywhere.

**Comment by Samuel-IH** [comment]
The herbs use the same logic as the corpses. When i added autodestruct to the corpses it also got added to the herbs. Oops.
