### ISSUE TITLE
Bags can't scrap if they have stuff in them.

### ISSUE THREAD

**Issue by BarchamMal** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#58]
**Is your feature request related to a problem? Please describe.**
It's quite grievous when I accidentally throw my dyes bag into a 10000° furnace and it immediately turns into leather and syenite.

**Describe the solution you'd like**
I think it'd be nice if bags could not be scrapped if they had stuff in them.

**Describe alternatives you've considered**
Or, you could make it scrap the bag and drop the stuff in the furnace. In the case of flowers this would just waste your bag, not you Elanor. In the case of ores or wood however it would be a tradeoff of bag for convenience.

**Comment by Samuel-IH** [comment]
Same fix as https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/issues/46

**Comment by Samuel-IH** [comment]
This issue was combined into a feature request, closing.
