### ISSUE TITLE
More than 2 tiers of gems

### ISSUE THREAD

**Issue by BarchamMal** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#59]
I noticed that diamond is very rare, compared to emerald, sapphire, topaz, etc.

It seems that right now the gems go like this:
1. Lowest level
    - Amethyst
    - Opal
    - Onyx
2. Medium Low level
    - Jade
    - Lapis Lazuli
    - Citrine
    - Emerald
3. Medium level
    - Sapphire
    - Black Sapphire
    - Ruby
    - Topaz
4. High level
    - Diamond

The way the gems should spawn/generate should be more like this:
These low level gems should be common:
 - Citrine
 - Jade
 - Onyx
 - Opal
 - Lapis Lazuli
 - Amethyst
 
 These high level gems should be rare:
  - Topaz
  - Emerald
  - Black Sapphire
  - Diamond
  - Sapphire
  - Ruby

**Comment by Samuel-IH** [comment]
Oops.
