### ISSUE TITLE
No Vengeful bonus with Mastercraft

### ISSUE THREAD

**Issue by Stridsvogn** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#6]
Using Vengeful Green Amulet & Vengeful Green Full Plate with Masterful Crafted Iron Battleaxe, there is no Vengeful set bonus for the 3 pieces.

"Masterful items are unique in that they are capable of attaining higher set bonuses and count as VENGEFUL for the purposes of synergizing."

Not sure if this is a bug or if the quoted text is misleading and that it will only count as Vengeful if all 3 slots are Masterful. The way it's written makes it seem like Masterful will count as Vengeful for set bonuses, similar to how Brilliant items count as Vengeful for generic Vengeful set bonus.

**Comment by Samuel-IH** [comment]
This is a planned feature which is not implemented yet. It will be closed when it is completed.

**Comment by Samuel-IH** [comment]
This has been completed and is now available on the alpha server. Newly crafted items will receive set bonuses.
