### ISSUE TITLE
Mastery, Speed, and Harvesting are only class skills for the default classes

### ISSUE THREAD

**Issue by BarchamMal** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#60]
Not sure if this is a bug or intended, but Craft: Mastery, Craft: Harvesting, and Craft: Speed are only Class skills for the default classes.

**Comment by BarchamMal** [comment]
Not for weapon master, elite guard, palemaster, etc.

**Comment by Samuel-IH** [comment]
Not intended. May revisit this in the future who knows.
