### ISSUE TITLE
ATS Boot conversion

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#65]
I have most ATS boots available in my vault, I can produce a complete list if necessary.

After conversion I got 15 crafted yellow and 3 crafted Red boots.

Seems like most of the boot varieties are going to yellow.  

david

**Comment by Samuel-IH** [comment]
Works as intended. All of the ATS boots sit within the 11-21 range, which only encompasses red, blue and yellow gts counterparts.
The tags for the ATS boots are rather messy and not worth my time to put more effort into them beyond these two versions.

Thank you for bringing this up though!
