### ISSUE TITLE
Crafting select tree

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#68]
Example:
When I select to craft a Spear I scroll down to Spear.  After I click on it, the scrollbar resets to the top so I"m back on axe.

Not a big thing, but annoying to have to scroll back down everytime I select a new weapon.  Can we have the scroll bar not reset? 

When I select a particular weapon in the tree that scrollbar doesn't reset.

david

**Comment by Samuel-IH** [comment]
I feel your pain, but this is something that we can't fix. Game APIs don't give us a way to control the scroll offsets.
