### ISSUE TITLE
Canceling 100x crafting is done one at a time

### ISSUE THREAD

**Issue by ExtraneousVariable** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#7]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release
Windows 10

**Describe the bug**
When crafting 100x of something and you want to cancel, you can walk away which stops the crafting but it leaves the GUI window up.  The only way to cancel the 99 remaining is 99 clicks.  Clicking the X should cancel the whole queue for that item, not just one at a time.

**To Reproduce**
Queue up 100 of something, then walk away.  GUI doesn't go away, queue remains, have to cancel one by one.

**Screenshots**
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/29b4eba2-06a5-4acd-8164-0f5048608df5)

**Comment by Samuel-IH** [comment]
Intended! You can queue up things from entirely different trades and walk to a from crafting stations to automatically continue.

To cancel them all at once you need to right click them which doesn't seem to be working at the moment so I'll leave this issue open.

**Comment by Samuel-IH** [comment]
This is fixed and you can now right-click on the 'x' button to cancel all 100 of them at the same time.
The fix will be available next time the alpha server is patched.
