### ISSUE TITLE
Whips don't have disarm

### ISSUE THREAD

**Issue by Samuel-IH** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#73]
Seems someone forgot to add disarm to them. I'm on me phone atm so I'm not gonna type all the details.

**Comment by BarchamMal** [comment]
Well, if you're not otp atm, what does that mean "don't have disarm"?

**Comment by Samuel-IH** [comment]
@BarchamMal Whips normally have the disarm feat. I forgot to add that in GTS whips.

**Comment by Samuel-IH** [comment]
Fixed and will be available when we patch in some other pending item changes
