### ISSUE TITLE
Moonflower is too rare

### ISSUE THREAD

**Issue by BarchamMal** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#74]
I'm not sure if you'll fix this, but there is a serious bottle neck at the beginning of tailoring.
Moon flower is close to (maybe twice as common?) as Elanor.
This seems wrong because it's right at the beginning of crafting and should be common.

> I want them all to be pretty common, except--what's it called?-- Niphredil. and Elanor. The last ones.
@Samuel-IH

**Comment by Samuel-IH** [comment]
@BarchamMal What's this quote?

**Comment by BarchamMal** [comment]
@Samuel-IH That is what you said to me when we were deciding how rare and *where* the different herbs would be.

**Comment by TomRotfl** [comment]
Is this still valid? If so I can look at Moonflower spawn settings and adjust accordingly

**Comment by BarchamMal** [comment]
Yes, I believe it is.

Moonflower seems common enough when you examine it... But after looking at the flower of two tiers later, Red Sumac, I think Moonflower is a bit too rare.
It seems like there were more Moonflower on the server than normal, Goon may have tweaked it, or it could just be RNG.
At the time of this comment there were 75 Moonflowers on the server, while there were 382 Red Sumac.

**Comment by Samuel-IH** [comment]
I have not addressed this issue so it still exists. If you want to fix it @TomRotfl that would be wonderful and save me some time.

**Comment by BarchamMal** [comment]
As this issue was fixed in the patch of [May 3rd 2024](https://www.adawnofheroes.org/docs/patch-note-may-3-2024/) I'm closing this now.
