### ISSUE TITLE
PADDED and LEATHER armor are inverted

### ISSUE THREAD

**Issue by TomRotfl** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#76]
It seems like Padded and Leather armor on GTS are inverted, so if you craft an armor named "Leater", you are actually crafting a "Padded", and viceversa.

Original post with details [HERE](https://discord.com/channels/417346233749995520/417346665058402307/1229668039390138408)

**Comment by Samuel-IH** [comment]
Fixed, will be available next time we patch the items in (and migrate)
