### ISSUE TITLE
Can't smelt Coldiron

### ISSUE THREAD

**Issue by Stridsvogn** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#8]
So I've been trying to smelt Coldiron Ore in the forge, same as Copper and Iron.
Nothing happens when I put Coldiron Ore in the forge while it's hot. 

Had 2400+ degrees  after smelting a bunch of Copper and Iron, nothing happened, the fuel just kept burning without smelting anything.
Tried different types of logs for fuel, as I can see when examining the wood types that Pine and  Cedar are "Burnable Material: 1" and Elm is "Burnable Material: 3", but nothing worked. Even tried adding Charcoal, knowing that in the real world charcoal burns hotter than wood, so I figured there'd be some sort of synergy with it in smelting, but no joy.

Is this a bug or is there some special wood type I need to hunt down to smelt Coldiron specifically?

**Comment by Samuel-IH** [comment]
The coldiron needs to be alloyed with charcoal. So you need wood, charcoal, and coldiron ore in there.

Please test and if that works then I'll close this issue.

**Comment by Stridsvogn** [comment]
Tried with every type of wood (except Snekwood, can't find it anywhere, spent about 2 hours searching). Burned through a few hundred logs of wood, not a single ingot was smelted.

![not smelting](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/156006813/50c846ed-8723-4a29-a470-291797ed68fd)

**Comment by Stridsvogn** [comment]
Just tried smelting Verdicite, Shadow Ore, Rubecite and Syenite and Mithral as well. Only Mithral will smelt out of those 5, Verdicite, Shadow Ore, Rubecite and Syenite just burns away the wood with no smelting.

**Comment by Samuel-IH** [comment]
Fixed on development. The fix for this will be available next time we patch the alpha server.
