### ISSUE TITLE
Animals not originally GTS and that have the `gts-carcass-drop` OnDeath create a dead carcass but without dead position/animation

### ISSUE THREAD

**Issue by TomRotfl** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#81]
Spawn a Legendary Bear from the toolset, it has the `gts-carcass-drop` flag, so OnDeath it generates a GTS carcass.
When it dies, it re-generates the creature body as carcass, but standing still, not on dead position.

![Screenshot 2024-07-08 123940](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/60175349/e482a9ec-832e-4384-b4bb-a80cad2c3bed)

**Comment by BarchamMal** [comment]
I've also noticed a (possibly) related issue where if they were dominated when they died, they're dead body (standing up) will still be in the party and follow the player who dominated them, but not moving, just teleporting when the player goes through transitions.
