### ISSUE TITLE
GTS Assets to spawn/de-spawn from areas when players enter/leave it

### ISSUE THREAD

**Issue by TomRotfl** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#83]
To further improve performances and remove hundreds of objects from the master objects list, it would probably be wise to have GTS Assets spawn inside of an area only when a player loads the area (if no one is already in that area).

Similarly, it would need GTS assets to de-spawn from an area, when left empty.

Similar code is already on the nwscript part for NPCs spawn/despawn on area load/unload.
To handle that on NWScript I would just need the API to Spawn the GTS assets on an area, and to de-spawn them if there are special checks to do, otherwise I can potentially already do the de-spawn from NWScript.

You can check [#scripts/hc_on_sendarea.nss for examples.](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/adoh-scripts/blob/eb05fae4fd64ce0221cd961fedb3c57eced37f9a/scripts/hc_on_sendarea.nss#L137)

**Comment by Samuel-IH** [comment]
Not something that can be done from NwScript because GTS uses the component system: https://github.com/Samuel-IH/Goon-ComponentSystem

Very good idea though! Should be pretty straightforward to implement.
