### ISSUE TITLE
Crafting queue - Drop materials, crafting keeps going

### ISSUE THREAD

**Issue by ExtraneousVariable** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#9]
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release
Windows 10

**Describe the bug**
When queuing a bunch of items to craft, if you drop the materials it doesn't STOP the queue.  It keeps processing.  Nothing is produced, skills don't increase, but the countdown keeps going.

**To Reproduce**
Queue items, drop materials, queue keeps counting down.  Items required show up negative in red.

**Screenshots**
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/286b8e45-5a45-4d9e-bcd0-fbf2b7b51432)

**Comment by ExtraneousVariable** [comment]
Once you get into a negative queue condition, even picking the ingots etc back up doesn't "reset" the needed materials.  
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/1f44daea-cb47-47b8-9a1f-71abfddc11ba)

**Comment by ExtraneousVariable** [comment]
If you log off and log back in again, it resets properly.
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/a56c0d3a-ea0c-4426-9ff6-0b91495fc6d4)

**Comment by Samuel-IH** [comment]
I see this as an edge case. For optimization purposes this wont be fixed.
